# Site settings
title: Rosendo Peña Hernández
description: 'Desarrollador de Software - Músico y Productor'
url: 'http://ropherpanama.github.io/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Rosendo Peña Hernández'
  email: ropherpanama@gmail.com
#  twitter_username: ropherpanama
#  facebook_username: ropherpanama
  github_username:  ropherpanama
  linkedin_username:  ropherpanama

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
